global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'kubelet'
    static_configs:
      - targets: ['localhost:10255']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['localhost:9091']
