name: Sensor Data Ingestion

on:
  # Ejecuta el workflow en cada push a la rama main
  push:
    branches: [ main ]
  # También puedes ejecutarlo manualmente o en otros eventos
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # O la versión de Python que uses

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the service
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000

    - name: Run ESLint
      run: |
        npm install
        npx eslint .

    - name: Run Pylint
      run: |
        pip install pylint
        pylint **/*.py

    - name: Run SonarQube analysis
      run: |
        sonar-scanner
